{% set name = "django-axes" %}
{% set version = "5.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5da489478bd89a3e2386a5a2d470f94b1f4ede2244089725cd69ec47d005ad0f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - setuptools
    - python
    - django >=2.0
    - django-appconf >=1.0.3
    - django-ipware >=3,<4

test:
  imports:
    - axes

about:
  home: https://pypi.org/project/django-axes/
  summary: django-axes, User lockout in django apps.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
