{% set name = "django-axes" %}
{% set version = "7.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fb0819dff6ee71d9e532a32ce168451255e37010f2e60ee62e1da4d6599126da

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools_scm
  run:
    - setuptools
    - python >=3.8
    - asgiref >=3.6.0
    - django >=3.2
    - django-ipware >=3

test:
  imports:
    - axes

about:
  home: https://pypi.org/project/django-axes/
  summary: django-axes, User lockout in django apps.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
