{% set name = "django-axes" %}
{% set version = "7.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 16121bbb7bacf1ed83f23a4800ac168707ffce014407df1049aa4f2ea28d3d52

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - setuptools
    - python >={{ python_min }}
    - asgiref >=3.6.0
    - django >=3.2
    - django-ipware >=3

test:
  requires:
    - python {{ python_min }}
  imports:
    - axes

about:
  home: https://pypi.org/project/django-axes/
  summary: django-axes, User lockout in django apps.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
