{% set name = "django-axes" %}
{% set version = "6.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57d29f16ca46a8e7c99252d710bf36412e35f12f338faac25f2f547618f328e8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools_scm
  run:
    - setuptools
    - python >=3.8
    - django >=3.2
    - django-ipware >=3

test:
  imports:
    - axes

about:
  home: https://pypi.org/project/django-axes/
  summary: django-axes, User lockout in django apps.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
